apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ks-releaser-source-shared-storage
spec:
  resources:
    requests:
      storage: 16Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
